version: '3.9'

volumes:
  mydomain-maildir:


services:
  receiver-smtp-msa:
    hostname: smtp-msa.mydomain.tld
    build:
      context: .
      dockerfile_inline: |
        # syntax=docker/dockerfile:1
        FROM vsmtp-receiver:dev
        ## saslauthd is used internally by vsmtp
        RUN apt-get update && apt-get install -y sasl2-bin openssl

        RUN sed -i 's/START=no/START=yes/g' /etc/default/saslauthd
        RUN sed -i 's/MECHANISMS="pam"/MECHANISMS="shadow"/g' /etc/default/saslauthd

        RUN useradd -p $(openssl passwd -1 john.doe) john.doe@mydomain.tld

        # RUN usermod -a -G sasl vsmtp
        # USER vsmtp
    command: sh -c "saslauthd -a shadow && vsmtp-receiver"
    volumes:
      - ../prelude.rhai:/prelude.rhai:ro
      - ./receiver/config.rhai:/etc/vsmtp/receiver-smtp/conf.d/config.rhai:ro
      - ./receiver/rules-pre-av.rhai:/rules.rhai:ro
      - ../broker/generated/rootCA.crt:/etc/ssl/certs/ca-certificates.crt:ro
      - ./receiver/generated/smtp-msa.mydomain.tld.crt:/etc/ssl/certs/smtp-msa.mydomain.tld.crt:ro
      - ./receiver/generated/smtp-msa.mydomain.tld.key:/etc/ssl/certs/smtp-msa.mydomain.tld.key:ro
    networks:
      net:
        ipv4_address: 172.23.0.3
    ports:
      - 127.0.0.1:10025:25
      - 127.0.0.1:10587:587
      - 127.0.0.1:10465:465
    depends_on:
      broker:
        condition: service_healthy

  mydomain-working:
    image: vsmtp-working:dev
    command: vsmtp-working --config /etc/vsmtp/working/conf.d/config.rhai
    volumes:
      - ../broker/generated/rootCA.crt:/etc/ssl/certs/ca-certificates.crt:ro
      - ./working/config.rhai:/etc/vsmtp/working/conf.d/config.rhai:ro
      - ./working/rules.rhai:/rules.rhai:ro
      - ./working/rsa-private-key.pem:/rsa-private-key.pem:ro
      - ./working/ed25519-private-key.pem:/ed25519-private-key.pem:ro
      - ./working/dkim-private-key.rhai:/dkim-private-key.rhai:ro
    networks: [ net ]
    depends_on:
      broker:
        condition: service_healthy
      clamav:
        condition: service_healthy

  mydomain-delivery-maildir:
    build:
      context: .
      dockerfile_inline: |
        # syntax=docker/dockerfile:1
        FROM vsmtp-maildir:dev
        RUN apt-get update && apt-get install -y openssl
        RUN useradd -p $(openssl passwd -1 john.doe) --create-home john.doe@mydomain.tld
    volumes:
      - ./maildir/config.rhai:/etc/vsmtp/maildir/conf.d/config.rhai:ro
      - ../broker/generated/rootCA.crt:/etc/ssl/certs/ca-certificates.crt:ro
      - mydomain-maildir:/home:rw
    networks: [ net ]
    depends_on:
      broker:
        condition: service_healthy

  mydomain-imap:
    build:
      context: .
      dockerfile_inline: |
        # syntax=docker/dockerfile:1
        FROM dovecot/dovecot
        RUN apt-get update && apt-get install -y openssl
        RUN useradd -p $(openssl passwd -1 john.doe) john.doe@mydomain.tld
    ports:
      # - 127.0.0.1:10110:110 # POP3
      # - 127.0.0.1:10995:995 # POP3S
      - 127.0.0.1:10143:143 # IMAP
      # - 127.0.0.1:10993:993 # IMAPS
    volumes:
      - mydomain-maildir:/home:rw
      - ./dovecot.conf:/etc/dovecot/dovecot.conf:ro

  mydomain-basic:
    image: vsmtp-basic:dev
    hostname: out-v0.mydomain.tld
    volumes:
      - ./basic/config.rhai:/etc/vsmtp/basic/conf.d/config.rhai:ro
      - ../broker/generated/rootCA.crt:/etc/ssl/certs/ca-certificates.crt:ro
    networks:
      net:
        ipv4_address: 172.23.0.10
    depends_on:
      broker:
        condition: service_healthy
      dns-server:
        condition: service_healthy

  clamav:
    image: clamav/clamav:1.1
    networks: [ net ]
    healthcheck:
      test: sh -c "[[ \"$(echo PING | nc localhost 3310)\" = \"PONG\" ]] || exit 1"
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 0s

  mydomain-log-dispatcher:
    image: vsmtp-log-dispatcher:dev
    # environment:
    #   - JAEGER=telemetry:6831
    #   - LOKI_URL=http://loki:3100
    volumes:
      - ../broker/generated/rootCA.crt:/etc/ssl/certs/ca-certificates.crt:ro
      - ./logs/config.rhai:/etc/vsmtp/log-dispatcher/conf.d/config.rhai
      - /run/systemd/journal/socket:/run/systemd/journal/socket
    networks:
      - net
      # - jaeger
      # - loki
    depends_on:
      broker:
        condition: service_healthy
