version: '3.9'

volumes:
  clamav-cache:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"

networks:
  vsmtp:


services:
  broker:
    image: vsmtp-broker:dev
    hostname: broker.mydomain.tld
    ports:
      - 127.0.0.1:15672:15672
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./definitions.json:/etc/rabbitmq/definitions.json:ro
    networks: [ vsmtp ]
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  receiver:
    image: vsmtp-receiver:dev
    hostname: receiver.mydomain.tld
    networks: [ vsmtp ]
    ports:
      - 127.0.0.1:10025:25
    depends_on:
      broker:
        condition: service_healthy
    volumes:
      - ./receiver.rhai:/etc/vsmtp/receiver-smtp/conf.d/config.rhai:ro
      - ./receiver-rules.rhai:/etc/vsmtp/receiver-smtp/filter.rhai:ro

  working:
    image: vsmtp-working:dev
    hostname: working.mydomain.tld
    networks: [ vsmtp ]
    volumes:
      - ./working.rhai:/etc/vsmtp/working/conf.d/config.rhai:ro
      - ./working-rules.rhai:/etc/vsmtp/working/script.rhai:ro
    depends_on:
      broker:
        condition: service_healthy

  forwarder:
    image: vsmtp-forward:dev
    networks: [ vsmtp ]
    volumes:
      - ./forwarder.rhai:/etc/vsmtp/forward/conf.d/config.rhai:ro
    depends_on:
      broker:
        condition: service_healthy
      clamsmtp:
        condition: service_healthy

  clamsmtp:
    hostname: clamsmtp.mydomain.tld
    networks: [ vsmtp ]
    build:
      context: .
      dockerfile_inline: |
        # syntax=docker/dockerfile:1
        FROM debian:stable-slim

        RUN apt-get update && \
            apt-get install -y clamsmtp net-tools && \
            apt-get clean && \
            rm -rf /var/lib/apt/lists/*

        RUN sed -i 's/^Listen: .*$/Listen: 0.0.0.0:10026/g' /etc/clamsmtpd.conf
        RUN echo "Action: pass" >> /etc/clamsmtpd.conf

        RUN sed -i 's/^User: .*$/User: clamav/g' /etc/clamsmtpd.conf
        RUN sed -i 's/^OutAddress: .*$/OutAddress: receiver.mydomain.tld:10025/g' /etc/clamsmtpd.conf
        RUN sed -i 's/^ClamAddress: .*$/ClamAddress: av.mydomain.tld:3310/g' /etc/clamsmtpd.conf

        RUN mkdir -p /var/spool/clamsmtp/
        RUN chown clamav:clamav /var/spool/clamsmtp/

        ## CMD ["/bin/bash", "-c", "cat /etc/clamsmtpd.conf && clamsmtpd -d 4 -f /etc/clamsmtpd.conf"]
        CMD ["/bin/bash", "-c", "clamsmtpd -d 4 -f /etc/clamsmtpd.conf"]
    volumes: [ clamav-cache:/var/spool/clamsmtp/:rw ]
    healthcheck:
      test: sh -c "netstat -an | grep 10026 > /dev/null; if [ 0 != $? ]; then exit 1; fi;"
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s
    depends_on:
      clamav:
        condition: service_healthy
      receiver:
        condition: service_started

  clamav:
    hostname: av.mydomain.tld
    networks: [ vsmtp ]
    build:
      context: .
      dockerfile_inline: |
        # syntax=docker/dockerfile:1
        FROM clamav/clamav:1.1
        ## Remove the User line of the clamd.conf file
        ## This is needed to run the clamav as root (do not drop privileges)
        RUN sed -i '/User clamav/d' /etc/clamav/clamd.conf
    volumes: [ clamav-cache:/var/spool/clamsmtp/:rw ]
    environment:
      - CLAMAV_NO_FRESHCLAMD=true
    healthcheck:
      test: sh -c "[[ \"$(echo PING | nc localhost 3310)\" = \"PONG\" ]] || exit 1"
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 0s
