[package]
name = "vsmtp-antivirus"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true
license = "Elastic-2.0"
license-file.workspace = true

[lints]
workspace = true

[dependencies]
rhai = { workspace = true }
