version: '3.9'

networks:
  mysql:


volumes:
  mytarget-maildir:


services:
  mytarget-receiver:
    image: vsmtp-receiver:dev
    hostname: smtp-in.mytarget.tld
    volumes:
      - ../prelude.rhai:/prelude.rhai:ro
      - ./receiver/config.rhai:/etc/vsmtp/receiver-smtp/conf.d/config.rhai:ro
      - ./receiver/rules.rhai:/rules.rhai:ro
      - ../broker/generated/rootCA.crt:/etc/ssl/certs/ca-certificates.crt:ro
      - ./receiver/generated/mytarget.tld.crt:/etc/ssl/certs/mytarget.tld.crt:ro
      - ./receiver/generated/mytarget.tld.key:/etc/ssl/certs/mytarget.tld.key:ro
    networks:
      net:
        ipv4_address: 172.23.0.5
      mysql:
    ports:
      - 127.0.0.1:11025:25 # Relay
      - 127.0.0.1:11587:587 # Submission
      - 127.0.0.1:11465:465 # SubmissionS
    depends_on:
      broker:
        condition: service_healthy
      mytarget-users-db:
        condition: service_healthy
    env_file:
      - broker-mytarget.env

  mytarget-users-db:
    image: mysql:8.0.34-debian
    volumes:
      - ./users.sql:/docker-entrypoint-initdb.d/users.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: vsmtp-dev
      MYSQL_PASSWORD: vsmtp-dev
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - mysql

  mytarget-working:
    image: vsmtp-working:dev
    command: vsmtp-working --config /etc/vsmtp/working/conf.d/config.rhai
    volumes:
      - ./working/config.rhai:/etc/vsmtp/working/conf.d/config.rhai:ro
      - ../broker/generated/rootCA.crt:/etc/ssl/certs/ca-certificates.crt:ro
      - ./working/rules.rhai:/rules.rhai:ro
    networks: [ net ]
    depends_on:
      broker:
        condition: service_healthy
    env_file:
      - broker-mytarget.env

  mytarget-basic:
    image: vsmtp-basic:dev
    hostname: smtp-out.mytarget.tld
    volumes:
      - ./basic/config.rhai:/etc/vsmtp/basic/conf.d/config.rhai:ro
      - ../broker/generated/rootCA.crt:/etc/ssl/certs/ca-certificates.crt:ro
      - ../mydomain.tld/receiver/generated/rootCA.crt:/etc/ssl/certs/mydomain.tld-root-ca.crt:ro
    networks:
      net:
        ipv4_address: 172.23.0.6
    depends_on:
      broker:
        condition: service_healthy
      dns-server:
        condition: service_healthy
    env_file:
      - broker-mytarget.env

  mytarget-delivery-maildir:
    build:
      context: .
      dockerfile_inline: |
        # syntax=docker/dockerfile:1
        FROM vsmtp-maildir:dev
        RUN apt-get update && apt-get install -y openssl
        RUN useradd -p $(openssl passwd -1 jenny.doe) --create-home jenny.doe@mytarget.tld
    volumes:
      - ./maildir/config.rhai:/etc/vsmtp/maildir/conf.d/config.rhai:ro
      - ../broker/generated/rootCA.crt:/etc/ssl/certs/ca-certificates.crt:ro
      - mytarget-maildir:/home:rw
    networks: [ net ]
    depends_on:
      broker:
        condition: service_healthy
    env_file:
      - broker-mytarget.env

  mytarget-imap:
    build:
      context: .
      dockerfile_inline: |
        # syntax=docker/dockerfile:1
        FROM dovecot/dovecot
        RUN apt-get update && apt-get install -y openssl
        RUN useradd -p $(openssl passwd -1 jenny.doe) jenny.doe@mytarget.tld
    ports:
      # - 127.0.0.1:11110:110 # POP3
      # - 127.0.0.1:11995:995 # POP3S
      - 127.0.0.1:11143:143 # IMAP
      # - 127.0.0.1:11993:993 # IMAPS
    volumes:
      - mytarget-maildir:/home:rw
      - ./dovecot.conf:/etc/dovecot/dovecot.conf:ro
    depends_on:
      mytarget-delivery-maildir:
        condition: service_started

  mytarget-log-dispatcher:
    image: vsmtp-log-dispatcher:dev
    volumes:
      - ../broker/generated/rootCA.crt:/etc/ssl/certs/ca-certificates.crt:ro
      - ./logs/config.rhai:/etc/vsmtp/log-dispatcher/conf.d/config.rhai:ro
    networks: [ net ]
    depends_on:
      broker:
        condition: service_healthy
    env_file:
      - broker-mytarget.env
