version: '3.9'

networks:
  # loki:
  # jaeger:
  demo_net:
    external: true

# volumes:
#   grafana-data:


services:
  mydomain-log-dispatcher:
    image: vsmtp-log-dispatcher:dev
    # environment:
    #   - JAEGER=telemetry:6831
    #   - LOKI_URL=http://loki:3100
    volumes:
      - ./config/broker/generated/rootCA.crt:/etc/ssl/certs/ca-certificates.crt:ro
      - ./config/mydomain.tld/logs/config.rhai:/etc/vsmtp/log-dispatcher/conf.d/config.rhai
    networks:
      - demo_net
      # - jaeger
      # - loki
    depends_on:
      broker:
        condition: service_healthy

  mytarget-log-dispatcher:
    image: vsmtp-log-dispatcher:dev
    # environment:
    #   - JAEGER=telemetry:6831
    #   - LOKI_URL=http://loki:3100
    volumes:
      - ./config/broker/generated/rootCA.crt:/etc/ssl/certs/ca-certificates.crt:ro
      - ./config/mytarget.tld/logs/config.rhai:/etc/vsmtp/log-dispatcher/conf.d/config.rhai
    networks:
      - demo_net
      # - jaeger
      # - loki
    depends_on:
      broker:
        condition: service_healthy
  # telemetry:
  #   image: jaegertracing/all-in-one:latest
  #   networks:
  #     - jaeger
  #   ports:
  #     - 6831/udp
  #     - 6832/udp
  #     - 127.0.0.1:16686:16686
  #
  # loki:
  #   image: grafana/loki:2.8.0
  #   ports:
  #     - "3100:3100"
  #   command: -config.file=/etc/loki/local-config.yaml
  #   networks:
  #     - loki
  #
  # promtail:
  #   image: grafana/promtail:2.8.0
  #   command: -config.file=/etc/promtail/config.yml
  #   networks:
  #     - loki
  #
  # grafana:
  #   image: grafana/grafana:latest
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - loki
  #   environment:
  #     - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
  #     - GF_AUTH_ANONYMOUS_ENABLED=true
  #     - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
  #   entrypoint:
  #     - sh
  #     - -euc
  #     - |
  #       mkdir -p /etc/grafana/provisioning/datasources
  #       cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
  #       apiVersion: 1
  #       datasources:
  #       - name: Loki
  #         type: loki
  #         access: proxy
  #         orgId: 1
  #         url: http://loki:3100
  #         basicAuth: false
  #         isDefault: true
  #         version: 1
  #         editable: false
  #       EOF
  #       /run.sh
  #
